# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11HKY1TUohgM66d--ZiAJzVYDLEB0Bsgb
"""

from init import app, jsonify, bcrypt, request
from auth import requires_auth,get_token
from Appdb import User, News


@app.route("/user", methods=['POST'])
@requires_auth
def user_view():
    """
    User endpoint, can only be accessed by an authorized user
    """
    data = request.json

    # Check if 'user' key exists in the JSON data
    if 'user' in data:
        username = data['user']
        return f"Received username: {username}"
    else:
        return "No username provided in the request"


@app.route('/login', methods=['POST'])
def login():
    data = get_token()
    return data


@app.route('/', methods=['POST'])
def index_view():
    return jsonify(msg="hello world")


if __name__ == "__main__":
    app.run(debug=True)
